<script setup lang="ts">
import { onLoad } from '@dcloudio/uni-app'
import { ref } from 'vue'
import { manageApi } from '../../../api/manage'
import AdminGuard from '../../../components/admin/AdminGuard.vue'
import StatusBadge from '../../../components/admin/StatusBadge.vue'
import { authStore } from '../../../stores/auth'
import { buildStrategyActions } from '../../../services/adminWorkflow'
const detail = ref<any>({}); const chunks = ref<any[]>([]); const logs = ref<any[]>([]); const strategy = ref<any>({}); const documentId = ref(''); const message = ref(''); const confirmedPlanId = ref<string | number | null>(null)
async function load() { try { detail.value = await manageApi.queryDocumentDetail(documentId.value); strategy.value = await manageApi.queryStrategyPlan(documentId.value); confirmedPlanId.value = Number(detail.value.strategyStatus) === 3 ? detail.value.currentPlanId : null; const page: any = await manageApi.queryDocumentChunks({ documentId: documentId.value, pageNo: 1, pageSize: 20 }); chunks.value = page?.records || []; if (detail.value.latestTaskId) { const task: any = await manageApi.queryTaskLogs({ taskId: detail.value.latestTaskId, pageNo: 1, pageSize: 20 }); logs.value = task?.logs || [] } } catch (e) { message.value = e instanceof Error ? e.message : '加载失败' } }
onLoad(async (query) => { documentId.value = String(query?.documentId || ''); if (documentId.value && (await authStore.guard('/pages/admin/documents/detail')) && authStore.isAdmin) await load() })
async function confirmStrategy() { try { const actions = buildStrategyActions(documentId.value, strategy.value); const result: any = await manageApi.confirmStrategy(actions.confirm); confirmedPlanId.value = result?.planId || actions.build.planId; message.value = '策略已确认'; await load() } catch (e) { message.value = e instanceof Error ? e.message : '操作失败' } }
async function buildIndex() { if (!confirmedPlanId.value) { message.value = '请先确认策略方案'; return }; try { await manageApi.buildIndex({ documentId: documentId.value, planId: confirmedPlanId.value }); message.value = '索引构建任务已提交'; await load() } catch (e) { message.value = e instanceof Error ? e.message : '操作失败' } }
</script>
<template><AdminGuard route="/pages/admin/documents/detail"><view class="page"><text class="title">文档详情</text><text v-if="message" class="error">{{ message }}</text><text class="name">{{ detail.documentName || detail.originalFileName || documentId }}</text><StatusBadge :status="detail.parseStatusName || detail.parseStatus" /><view class="actions"><button size="mini" :disabled="!strategy.planReady" @click="confirmStrategy">确认策略</button><button size="mini" type="primary" :disabled="!confirmedPlanId" @click="buildIndex">构建索引</button></view><text class="section">父块策略</text><view v-for="step in (strategy.plan?.parentPipeline?.steps || [])" :key="step.stepNo" class="chunk">{{ step.strategyName || step.strategyType }}</view><text class="section">子块策略</text><view v-for="step in (strategy.plan?.childPipeline?.steps || [])" :key="step.stepNo" class="chunk">{{ step.strategyName || step.strategyType }}</view><text class="section">切块</text><view v-for="chunk in chunks" :key="chunk.chunkId || chunk.id" class="chunk">{{ chunk.content || chunk.text || JSON.stringify(chunk) }}</view><text class="section">任务日志</text><view v-for="log in logs" :key="log.id || log.time" class="chunk">{{ log.message || JSON.stringify(log) }}</view></view></AdminGuard></template><style scoped>.page{padding:32rpx}.title,.name{display:block;font-size:36rpx;font-weight:600;margin-bottom:20rpx}.actions{display:flex;gap:16rpx;margin:20rpx 0}.section{display:block;font-weight:600;margin-top:20rpx}.chunk{padding:20rpx 0;border-bottom:1rpx solid var(--color-border)}.error{color:#b91c1c}</style>
